CREATE DATABASE IF NOT EXISTS merc_game;

USE merc_game;

CREATE TABLE IF NOT EXISTS Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) DEFAULT 1000.00,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Games (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  gameType VARCHAR(20) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  selectedOption VARCHAR(20) NOT NULL,
  diceResults JSON NOT NULL,
  win BOOLEAN NOT NULL,
  finalBalance DECIMAL(10, 2) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id)
); 